<?php

declare(strict_types=1);

namespace MergeMultisite\Migration;

use MergeMultisite\Config\MergeConfig;
use MergeMultisite\Db\Connection;
use MergeMultisite\Support\Logger;

/**
 * Posts/pages/CPTs phase of the migration (PLAN.md §5 step 4, §7.1):
 * copies every included site's content posts — pages, posts, custom
 * post types — plus their postmeta and term_relationships into the
 * destination single site.
 *
 * What this phase does per post:
 *  - Remaps post_author via the users IdMap (falling back to the
 *    configured destination admin, counted in the report).
 *  - Regenerates the GUID (`{destination_url}/?p={new_id}`, WP's
 *    standard form for posts) via GuidGenerator.
 *  - Resolves the destination post_name: configured contact-page
 *    variants canonicalize to `/contact/` (ContactPageCanonicalizer),
 *    then the slug is made unique within its post type the way
 *    WordPress's wp_unique_post_slug appends `-2`, `-3`, ... — a
 *    slightly stricter-than-WP global rule (WP allows duplicate slugs
 *    under different parents for hierarchical types) that is safe
 *    after merging N independent sites; every rename is reported.
 *  - Rewrites post_content block attributes (`wp:image {"id":...}`,
 *    `wp:gallery {"ids":[...]}`, `wp:navigation {"ref":...}`) through
 *    BlockAttributeRewriter.
 *  - Copies postmeta key-for-key; `_thumbnail_id` is remapped through
 *    the attachments IdMap (unmapped values are kept verbatim and
 *    counted). Other serialized/plugin-owned meta is copied verbatim —
 *    per-plugin rewriting is Phase 7's adapter work.
 *  - Writes term_relationships: each post's original categories/tags
 *    (remapped via the terms IdMap) PLUS the new top-level site
 *    category (PLAN.md §6).
 *
 * Two-pass parent handling (PLAN.md §7.1): rows are inserted with
 * post_parent = 0, then after all of a site's batches commit, a
 * per-site fixup pass resolves every parent through the posts IdMap —
 * including attachment posts, whose parents MediaMigrator (Phase 4)
 * deliberately left at 0 for this phase to repair. Term counts on the
 * destination are refreshed per site so wp-admin shows correct
 * numbers.
 *
 * Post statuses: `trash` and `auto-draft` are always discarded —
 * trashed drafts/posts are deleted content, not content to preserve —
 * plus the configured `excluded_post_statuses`; everything else
 * migrates, including drafts (works in progress) and `future` (each
 * future post is listed in the report for the Phase 5
 * schedule-future-posts workflow; PLAN.md §7.1). Discarded trash is
 * counted per site as `trash_skipped` so the report stays honest.
 *
 * Built-in excluded post types (on top of config):
 * attachment (Phase 4), revision, nav_menu_item + wp_navigation
 * (Phase 7 menus), customize_changeset (transient).
 *
 * Idempotent like the other phases: every row is recorded in
 * IdMap/MigrationTable ('post'), so a prewarmed re-run skips.
 *
 * @phpstan-type PostMigrationReport array{
 *     posts_migrated: int,
 *     posts_skipped: int,
 *     posts_failed: int,
 *     meta_rows_written: int,
 *     relationships_written: int,
 *     relationships_unmapped: int,
 *     site_category_assignments: int,
 *     parents_fixed: int,
 *     parents_unresolved: int,
 *     authors_fallback: int,
 *     thumbnails_unmapped: int,
 *     slug_renames: array<int, array{blog_id: int, post_id: int, post_type: string, old_slug: string, new_slug: string}>,
 *     contact_canonicalized: array<int, array{blog_id: int, post_id: int, old_slug: string, new_slug: string}>,
 *     trash_skipped: int,
 *     future_posts: array<int, array{blog_id: int, post_id: int, title: string, date_gmt: string}>,
 *     warnings: array<int, string>,
 *     by_site: array<int, array{posts: int}>
 * }
 *
 * @package MergeMultisite
 */
final class PostMigrator {

	/**
	 * Post types never handled here (their phases own them).
	 */
	private const BUILT_IN_EXCLUDED_POST_TYPES = array(
		'attachment',          // Phase 4 (MediaMigrator).
		'revision',            // Never content; regenerated by WP.
		'nav_menu_item',       // Phase 7 (menus).
		'wp_navigation',       // Phase 7 (block menus).
		'customize_changeset', // Transient Customizer data.
	);

	/**
	 * Block-attribute remapping for post_content: `ref` is a post ID
	 * (wp:navigation, wp:block), `id`/`ids` are attachment IDs
	 * (wp:image, wp:media-text, wp:gallery).
	 *
	 * @var array<string, string>
	 */
	private const BLOCK_REF_ATTRIBUTES = array(
		'ref' => 'post',
		'id' => 'attachment',
		'ids' => 'attachment',
	);

	/**
	 * Postmeta keys whose value is a single ID that must be remapped
	 * through the attachments IdMap.
	 */
	private const THUMBNAIL_META_KEY = '_thumbnail_id';

	public function __construct(
		private readonly ?BlockAttributeRewriter $blockRewriter = null,
	) {
	}

	/**
	 * Runs the post migration phase.
	 *
	 * @param Site[] $sites Included sites only.
	 *
	 * @return PostMigrationReport
	 *
	 * @throws \Throwable When destination database writes fail (rolled back first).
	 */
	public function migrate(
		Connection $source,
		Connection $destination,
		MergeConfig $config,
		array $sites,
		IdMap $idMap,
		MigrationTable $mapTable,
		bool $dryRun,
		Logger $logger
	): array {
		$blockRewriter = $this->blockRewriter ?? new BlockAttributeRewriter();

		$destPostsTable = $destination->siteTable( 'posts', 1 );
		$destPostMetaTable = $destination->siteTable( 'postmeta', 1 );
		$destTaxonomyTable = $destination->siteTable( 'term_taxonomy', 1 );
		$destRelationshipsTable = $destination->siteTable( 'term_relationships', 1 );

		$report = array(
			'posts_migrated' => 0,
			'posts_skipped' => 0,
			'posts_failed' => 0,
			'meta_rows_written' => 0,
			'relationships_written' => 0,
			'relationships_unmapped' => 0,
			'site_category_assignments' => 0,
			'parents_fixed' => 0,
			'parents_unresolved' => 0,
			'authors_fallback' => 0,
			'thumbnails_unmapped' => 0,
			'slug_renames' => array(),
			'contact_canonicalized' => array(),
			'trash_skipped' => 0,
			'future_posts' => array(),
			'warnings' => array(),
			'by_site' => array(),
		);
		$warnings = array(); // collected separately so warn() never widens $report's shape

		// Destination slugs in use per post type: pre-existing rows
		// plus every slug assigned during this run (shared across
		// sites, so site 2's "about" dedupes against site 1's).
		$slugUse = $this->collectDestinationSlugs( $destination, $destPostsTable );

		foreach ( $sites as $site ) {
			$blogId = $site->blogId;
			$postsTable = $source->siteTable( 'posts', $blogId );
			$postMetaTable = $source->siteTable( 'postmeta', $blogId );
			$relationshipsTable = $source->siteTable( 'term_relationships', $blogId );
			$taxonomyTable = $source->siteTable( 'term_taxonomy', $blogId );

			$rows = $this->fetchSourcePosts( $source, $postsTable, $config );
			$report['trash_skipped'] += $this->countTrashedPosts( $source, $postsTable, $config );
			if ( $rows === array() ) {
				continue;
			}

			// oldId => ['new_id' => int, 'old_parent' => int], resolved
			// in the second pass once every post of this site is in IdMap.
			$parentFixups = array();

			foreach ( array_chunk( $rows, max( 1, $config->batchSize ) ) as $batch ) {
				if ( ! $dryRun ) {
					$destination->beginTransaction();
				}

				try {
					$ids = array_map( static fn ( array $row ): int => (int) $row['ID'], $batch );
					$metaByPost = PostQueryHelper::fetchMetaForPosts( $source, $postMetaTable, $ids );
					$relationshipsByPost = $this->fetchRelationships( $source, $relationshipsTable, $taxonomyTable, $ids );

					foreach ( $batch as $row ) {
						$oldId = (int) $row['ID'];

						if ( $idMap->has( 'post', $blogId, $oldId ) ) {
							++$report['posts_skipped'];
							continue;
						}

						$meta = $metaByPost[ $oldId ] ?? array();

						$slug = $this->destinationSlug(
							(string) $row['post_name'],
							$config->contactPagePaths,
							$blogId,
							$oldId,
							(string) $row['post_type'],
							$slugUse,
							$report
						);

						if ( $dryRun ) {
							++$report['posts_migrated'];
							$report['by_site'][ $blogId ]['posts'] = ( $report['by_site'][ $blogId ]['posts'] ?? 0 ) + 1;
							$this->flagFuturePost( $row, $blogId, $oldId, $report );
							continue;
						}

						$content = (string) $row['post_content'];
						if ( $content !== '' ) {
							$content = $blockRewriter->rewrite( $content, $blogId, $idMap, self::BLOCK_REF_ATTRIBUTES );
						}

						try {
							$newId = $this->insertPost( $destination, $destPostsTable, $row, $content, $slug, $config, $idMap, $report );
							$this->updateGuid( $destination, $destPostsTable, $newId, $config->destinationUrl );
							$this->insertPostMeta( $destination, $destPostMetaTable, $newId, $meta, $blogId, $idMap, $report );
							$this->writeRelationships( $destination, $destRelationshipsTable, $newId, $relationshipsByPost[ $oldId ] ?? array(), $blogId, $idMap, $report );

							$siteCategoryTtId = $idMap->get( 'site_category', $blogId, 'category' );
							if ( $siteCategoryTtId !== null ) {
								$this->insertRelationshipRow( $destination, $destRelationshipsTable, $newId, $siteCategoryTtId );
								++$report['site_category_assignments'];
							} else {
								$this->warn( $warnings, $logger, sprintf( 'Site %d has no site-category mapping; posts were not tagged with the site category.', $blogId ) );
							}
						} catch ( \Throwable $e ) {
							++$report['posts_failed'];
							$this->warn( $warnings, $logger, sprintf( 'Post %d (site %d) failed: %s', $oldId, $blogId, $e->getMessage() ) );
							continue;
						}

						$idMap->set( 'post', $blogId, $oldId, $newId );
						$mapTable->record( $destination, 'post', $blogId, $oldId, $newId );

						$oldParent = (int) $row['post_parent'];
						if ( $oldParent > 0 ) {
							$parentFixups[ $oldId ] = array(
								'new_id' => $newId,
								'old_parent' => $oldParent,
							);
						}

						++$report['posts_migrated'];
						$report['by_site'][ $blogId ]['posts'] = ( $report['by_site'][ $blogId ]['posts'] ?? 0 ) + 1;
						$this->flagFuturePost( $row, $blogId, $oldId, $report );
					}

					if ( ! $dryRun ) {
						$destination->commit();
					}
				} catch ( \Throwable $e ) {
					if ( $destination->inTransaction() ) {
						$destination->rollBack();
					}
					$logger->error( sprintf( 'Post migration failed, rolled back: %s', $e->getMessage() ) );
					throw $e;
				}
			}

			// Second pass per site: parents (posts + attachments) and
			// term counts now that every post of this site is mapped.
			$this->fixParents( $source, $destination, $destPostsTable, $blogId, $parentFixups, $idMap, $dryRun, $report, $warnings, $logger );
			$this->refreshTermCounts( $destination, $destTaxonomyTable, $destRelationshipsTable, $dryRun );
		}

		$report['warnings'] = $warnings;

		$logger->info(
			sprintf(
				'Post migration%s: %d post(s) migrated, %d skipped (already mapped), %d failed, %d meta row(s), %d relationship(s), %d site-category assignment(s), %d parent fixup(s), %d unresolved parent(s), %d trash skipped, %d future.',
				$dryRun ? ' (dry run)' : '',
				$report['posts_migrated'],
				$report['posts_skipped'],
				$report['posts_failed'],
				$report['meta_rows_written'],
				$report['relationships_written'],
				$report['site_category_assignments'],
				$report['parents_fixed'],
				$report['parents_unresolved'],
				$report['trash_skipped'],
				count( $report['future_posts'] )
			)
		);

		return $report;
	}

	/**
	 * The destination post_name for one source post: contact variants
	 * canonicalize to `contact` first, then the slug is made unique
	 * within its post type (`-2`, `-3`, ...) against everything the
	 * destination already has or this run assigns. Empty slugs stay
	 * empty. Records canonicalizations and renames in the report.
	 *
	 * Public so the pure slug logic is unit-testable without a DB.
	 *
	 * @param string[]                          $contactPagePaths
	 * @param array<string, array<string, int>> $slugUse  post_type => slug => use count (by ref).
	 * @param PostMigrationReport               $report (by ref).
	 */
	public function destinationSlug(
		string $sourceSlug,
		array $contactPagePaths,
		int $blogId,
		int $postId,
		string $postType,
		array &$slugUse,
		array &$report
	): string {
		$slug = $sourceSlug;
		$canonicalized = false;

		if ( $slug !== '' && ContactPageCanonicalizer::isVariant( $slug, $contactPagePaths ) ) {
			$slug = ContactPageCanonicalizer::CANONICAL_SLUG;
			$canonicalized = true;
		}

		$final = $slug;
		if ( $slug !== '' ) {
			$base = $slug;
			$n = 2;
			while ( ( $slugUse[ $postType ][ $final ] ?? 0 ) > 0 ) {
				$final = $base . '-' . $n;
				++$n;
			}
			$slugUse[ $postType ][ $final ] = ( $slugUse[ $postType ][ $final ] ?? 0 ) + 1;
		}

		if ( $canonicalized ) {
			$report['contact_canonicalized'][] = array(
				'blog_id' => $blogId,
				'post_id' => $postId,
				'old_slug' => $sourceSlug,
				'new_slug' => $final,
			);
		} elseif ( $final !== $sourceSlug ) {
			$report['slug_renames'][] = array(
				'blog_id' => $blogId,
				'post_id' => $postId,
				'post_type' => $postType,
				'old_slug' => $sourceSlug,
				'new_slug' => $final,
			);
		}

		return $final;
	}

	/**
	 * All source posts eligible for this phase, ordered by ID so slug
	 * assignment is deterministic (lower IDs claim a slug first).
	 *
	 * Like the audit's PostQueryHelper::postStatusClause(), `trash` and
	 * `auto-draft` are always excluded — trashed posts are deleted
	 * content (counted via countTrashedPosts() for the report, never
	 * migrated); drafts migrate normally. The configured
	 * excluded_post_statuses apply on top.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	private function fetchSourcePosts( Connection $source, string $postsTable, MergeConfig $config ): array {
		$excludedStatuses = array_values( array_unique( array_merge( array( 'auto-draft', 'trash' ), $config->excludedPostStatuses ) ) );

		$params = array();
		$typeClause = $this->excludedPostTypeClause( $config, $params );
		$statusPlaceholders = array();
		foreach ( $excludedStatuses as $index => $status ) {
			$key = 'excluded_status_' . $index;
			$statusPlaceholders[] = ':' . $key;
			$params[ $key ] = $status;
		}

		// Both lists are never empty: the built-in excluded post types
		// and the always-excluded statuses guarantee that.
		$statusClause = 'post_status NOT IN (' . implode( ', ', $statusPlaceholders ) . ')';

		return $source->fetchAll(
			"SELECT * FROM {$postsTable} WHERE {$typeClause} AND {$statusClause} ORDER BY ID",
			$params
		);
	}

	/**
	 * The post_type NOT IN (...) fragment shared by the source fetch
	 * and the trash count: built-in excluded types (attachment,
	 * revision, menu, ...) plus the configured
	 * migration_excluded_post_types. (config.audit_excluded_post_types is
	 * audit/report suppression only — it does not stop migration.)
	 *
	 * @param array<string, string> $params Bound parameters, appended.
	 */
	private function excludedPostTypeClause( MergeConfig $config, array &$params ): string {
		$excludedTypes = array_values( array_unique( array_merge( self::BUILT_IN_EXCLUDED_POST_TYPES, $config->migrationExcludedPostTypes ) ) );

		$placeholders = array();
		foreach ( $excludedTypes as $index => $type ) {
			$key = 'excluded_post_type_' . $index;
			$placeholders[] = ':' . $key;
			$params[ $key ] = $type;
		}

		return 'post_type NOT IN (' . implode( ', ', $placeholders ) . ')';
	}

	/**
	 * How many otherwise-eligible posts on this site are trashed.
	 * Trash is discarded (deleted content), but the count is kept in
	 * the report so the discard is visible rather than silent.
	 */
	private function countTrashedPosts( Connection $source, string $postsTable, MergeConfig $config ): int {
		$params = array();
		$typeClause = $this->excludedPostTypeClause( $config, $params );

		return (int) $source->fetchScalar(
			"SELECT COUNT(*) FROM {$postsTable} WHERE {$typeClause} AND post_status = 'trash'",
			$params
		);
	}

	/**
	 * Every (post_type, post_name) already present on the destination,
	 * so the first migrated post with a slug keeps it and later ones
	 * dedupe exactly like they would in a running WordPress.
	 *
	 * @return array<string, array<string, int>> post_type => slug => count.
	 */
	private function collectDestinationSlugs( Connection $destination, string $postsTable ): array {
		$slugs = array();
		foreach ( $destination->fetchAll( "SELECT post_type, post_name FROM {$postsTable} WHERE post_name <> ''" ) as $row ) {
			$type = (string) $row['post_type'];
			$name = (string) $row['post_name'];
			$slugs[ $type ][ $name ] = ( $slugs[ $type ][ $name ] ?? 0 ) + 1;
		}

		return $slugs;
	}

	/**
	 * Insert one post row with post_parent = 0 (resolved in the second
	 * pass) and a blank GUID (set right after, since it embeds the new
	 * ID). post_content arrives already block-attribute-rewritten.
	 *
	 * @param array<string, mixed> $row
	 * @param PostMigrationReport  $report
	 */
	private function insertPost(
		Connection $destination,
		string $postsTable,
		array $row,
		string $content,
		string $slug,
		MergeConfig $config,
		IdMap $idMap,
		array &$report
	): int {
		$author = $idMap->get( 'user', 0, (int) $row['post_author'] );
		if ( $author === null ) {
			$author = $destination->config->adminUserId ?? 0;
			++$report['authors_fallback'];
		}

		$destination->execute(
			"INSERT INTO {$postsTable} (
                post_author, post_date, post_date_gmt, post_content, post_title,
                post_excerpt, post_status, comment_status, ping_status,
                post_password, post_name, to_ping, pinged,
                post_modified, post_modified_gmt, post_content_filtered,
                post_parent, guid, menu_order, post_type, post_mime_type,
                comment_count
            ) VALUES (
                :author, :date, :date_gmt, :content, :title,
                :excerpt, :status, :comment_status, :ping_status,
                :password, :name, :to_ping, :pinged,
                :modified, :modified_gmt, :content_filtered,
                0, '', :menu_order, :type, :mime,
                :comment_count
            )",
			array(
				'author'           => $author,
				'date'             => (string) $row['post_date'],
				'date_gmt'         => (string) $row['post_date_gmt'],
				'content'          => $content,
				'title'            => (string) $row['post_title'],
				'excerpt'          => (string) $row['post_excerpt'],
				'status'           => (string) $row['post_status'],
				'comment_status'   => (string) $row['comment_status'],
				'ping_status'      => (string) $row['ping_status'],
				'password'         => (string) $row['post_password'],
				'name'             => $slug,
				'to_ping'          => (string) $row['to_ping'],
				'pinged'           => (string) $row['pinged'],
				'modified'         => (string) $row['post_modified'],
				'modified_gmt'     => (string) $row['post_modified_gmt'],
				'content_filtered' => (string) $row['post_content_filtered'],
				'menu_order'       => (int) $row['menu_order'],
				'type'             => (string) $row['post_type'],
				'mime'             => (string) $row['post_mime_type'],
				'comment_count'    => (int) $row['comment_count'],
			)
		);

		return (int) $destination->lastInsertId();
	}

	/**
	 * Set the regenerated GUID (`?p={new_id}`) after the insert so it
	 * embeds the destination ID (PLAN.md §7.1).
	 */
	private function updateGuid( Connection $destination, string $postsTable, int $newId, string $destinationUrl ): void {
		$destination->execute(
			"UPDATE {$postsTable} SET guid = :guid WHERE ID = :id",
			array(
				'guid' => GuidGenerator::forPost( $destinationUrl, $newId ),
				'id' => $newId,
			)
		);
	}

	/**
	 * Copy all source postmeta onto the new post. `_thumbnail_id` is
	 * remapped through the attachments IdMap; everything else (plugin
	 * settings, serialized builders, ACF data) copies verbatim — those
	 * get per-plugin rewriting in Phase 7.
	 *
	 * @param array<string, string[]> $meta
	 * @param PostMigrationReport     $report
	 */
	private function insertPostMeta(
		Connection $destination,
		string $postMetaTable,
		int $newPostId,
		array $meta,
		int $blogId,
		IdMap $idMap,
		array &$report
	): void {
		foreach ( $meta as $metaKey => $values ) {
			foreach ( $values as $value ) {
				if ( $metaKey === self::THUMBNAIL_META_KEY ) {
					$value = $this->remapThumbnail( (string) $value, $blogId, $idMap, $report );
				}

				$destination->execute(
					"INSERT INTO {$postMetaTable} (post_id, meta_key, meta_value) VALUES (:post_id, :key, :value)",
					array(
						'post_id' => $newPostId,
						'key'     => $metaKey,
						'value'   => $value,
					)
				);
				++$report['meta_rows_written'];
			}
		}
	}

	/**
	 * Remap a `_thumbnail_id` value through the attachments IdMap. An
	 * unmapped value (attachment excluded/absent from this run) is kept
	 * verbatim rather than dropped, and counted for the report.
	 *
	 * @param PostMigrationReport $report
	 */
	private function remapThumbnail( string $value, int $blogId, IdMap $idMap, array &$report ): string {
		if ( ! is_numeric( $value ) ) {
			return $value;
		}

		$newId = $idMap->get( 'attachment', $blogId, (int) $value );
		if ( $newId === null ) {
			++$report['thumbnails_unmapped'];

			return $value;
		}

		return (string) $newId;
	}

	/**
	 * Write a post's original category/tag relationships, remapping each
	 * source term_taxonomy_id through the terms IdMap (keyed by the
	 * source term_id, matching TermMigrator). Duplicate destinations and
	 * unmapped terms are skipped (unmapped counted) rather than raising
	 * a primary-key violation.
	 *
	 * @param array<int, array<string, mixed>> $relationships
	 * @param PostMigrationReport              $report
	 */
	private function writeRelationships(
		Connection $destination,
		string $relationshipsTable,
		int $newPostId,
		array $relationships,
		int $blogId,
		IdMap $idMap,
		array &$report
	): void {
		$seen = array();
		foreach ( $relationships as $relationship ) {
			$destTtId = $idMap->get( 'term_taxonomy', $blogId, (int) $relationship['term_id'] );
			if ( $destTtId === null ) {
				++$report['relationships_unmapped'];
				continue;
			}
			if ( isset( $seen[ $destTtId ] ) ) {
				continue;
			}
			$seen[ $destTtId ] = true;

			$this->insertRelationshipRow( $destination, $relationshipsTable, $newPostId, $destTtId );
			++$report['relationships_written'];
		}
	}

	private function insertRelationshipRow( Connection $destination, string $relationshipsTable, int $objectId, int $termTaxonomyId ): void {
		$destination->execute(
			"INSERT INTO {$relationshipsTable} (object_id, term_taxonomy_id, term_order) VALUES (:object_id, :tt_id, 0)",
			array(
				'object_id' => $objectId,
				'tt_id'     => $termTaxonomyId,
			)
		);
	}

	/**
	 * Fetch every term relationship for a set of post IDs, chunked to
	 * stay under MySQL's 65535 parameter limit, JOINing term_taxonomy
	 * so the source term_id (the IdMap key TermMigrator records) is
	 * available alongside the relationship's term_taxonomy_id.
	 *
	 * @param int[] $postIds
	 *
	 * @return array<int, array<int, array{term_id:string}>>
	 */
	private function fetchRelationships( Connection $source, string $relationshipsTable, string $taxonomyTable, array $postIds ): array {
		$byPost = array();

		foreach ( array_chunk( $postIds, 5000 ) as $chunk ) {
			$placeholders = array();
			$params = array();
			foreach ( $chunk as $index => $postId ) {
				$key = 'object_id_' . $index;
				$placeholders[] = ':' . $key;
				$params[ $key ] = $postId;
			}

			$rows = $source->fetchAll(
				"SELECT tr.object_id, tt.term_id
                 FROM {$relationshipsTable} tr
                 INNER JOIN {$taxonomyTable} tt ON tt.term_taxonomy_id = tr.term_taxonomy_id
                 WHERE tr.object_id IN (" . implode( ', ', $placeholders ) . ')',
				$params
			);

			foreach ( $rows as $row ) {
				$byPost[ (int) $row['object_id'] ][] = $row;
			}
		}

		return $byPost;
	}

	/**
	 * Second pass: resolve every post_parent (posts inserted with 0,
	 * plus attachments whose parents MediaMigrator deferred) through
	 * the posts/attachments IdMap once all of a site's posts exist.
	 * Unresolved parents are left at 0 and warned about.
	 *
	 * @param array<int, array{new_id:int, old_parent:int}> $parentFixups
	 * @param PostMigrationReport                           $report
	 * @param string[]                                      $warnings
	 *
	 * @throws \Throwable When the parent-fixup transaction fails (rolled back first).
	 */
	private function fixParents(
		Connection $source,
		Connection $destination,
		string $destPostsTable,
		int $blogId,
		array $parentFixups,
		IdMap $idMap,
		bool $dryRun,
		array &$report,
		array &$warnings,
		Logger $logger
	): void {
		$updates = array();

		foreach ( $parentFixups as $fixup ) {
			$newParent = $idMap->get( 'post', $blogId, $fixup['old_parent'] )
				?? $idMap->get( 'attachment', $blogId, $fixup['old_parent'] );
			if ( $newParent === null ) {
				++$report['parents_unresolved'];
				$this->warn( $warnings, $logger, sprintf( 'Post %d (site %d): parent %d was not migrated; post_parent left 0.', $fixup['new_id'], $blogId, $fixup['old_parent'] ) );
				continue;
			}

			$updates[] = array(
				'id' => $fixup['new_id'],
				'parent' => $newParent,
			);
		}

		// Attachment parents (MediaMigrator wrote post_parent = 0 for
		// every attachment; see its docblock).
		$attachmentsTable = $source->siteTable( 'posts', $blogId );
		foreach ( $source->fetchAll( "SELECT ID, post_parent FROM {$attachmentsTable} WHERE post_type = 'attachment' AND post_parent > 0" ) as $row ) {
			$newId = $idMap->get( 'attachment', $blogId, (int) $row['ID'] );
			if ( $newId === null ) {
				continue;
			}

			$newParent = $idMap->get( 'post', $blogId, (int) $row['post_parent'] )
				?? $idMap->get( 'attachment', $blogId, (int) $row['post_parent'] );
			if ( $newParent === null ) {
				continue;
			}

			$updates[] = array(
				'id' => $newId,
				'parent' => $newParent,
			);
		}

		if ( $dryRun || $updates === array() ) {
			return;
		}

		$destination->beginTransaction();
		try {
			foreach ( $updates as $update ) {
				$destination->execute(
					"UPDATE {$destPostsTable} SET post_parent = :parent WHERE ID = :id",
					array(
						'parent' => $update['parent'],
						'id'     => $update['id'],
					)
				);
				++$report['parents_fixed'];
			}
			$destination->commit();
		} catch ( \Throwable $e ) {
			if ( $destination->inTransaction() ) {
				$destination->rollBack();
			}
			throw $e;
		}
	}

	/**
	 * Recompute wp_term_taxonomy.count from the relationships actually
	 * written, per site. TermMigrator inserts terms with count 0; this
	 * makes wp-admin category/tag counts correct once posts land.
	 */
	private function refreshTermCounts( Connection $destination, string $taxonomyTable, string $relationshipsTable, bool $dryRun ): void {
		if ( $dryRun ) {
			return;
		}

		$destination->execute(
			"UPDATE {$taxonomyTable} SET count = (
                SELECT COUNT(*) FROM {$relationshipsTable}
                WHERE {$relationshipsTable}.term_taxonomy_id = {$taxonomyTable}.term_taxonomy_id
            )"
		);
	}

	/**
	 * Record a `future`-status row in the report's future_posts list
	 * for the §7.1 schedule-future-posts workflow. (Trash never
	 * reaches this point — fetchSourcePosts excludes it.)
	 *
	 * @param array<string, mixed> $row
	 * @param PostMigrationReport  $report
	 */
	private function flagFuturePost( array $row, int $blogId, int $oldId, array &$report ): void {
		if ( (string) $row['post_status'] === 'future' ) {
			$report['future_posts'][] = array(
				'blog_id' => $blogId,
				'post_id' => $oldId,
				'title'   => (string) $row['post_title'],
				'date_gmt' => (string) $row['post_date_gmt'],
			);
		}
	}

	/**
	 * Log a warning and record it in the report.
	 *
	 * @param string[] $warnings
	 */
	private function warn( array &$warnings, Logger $logger, string $message ): void {
		$warnings[] = $message;
		$logger->warning( $message );
	}
}
