<?php

declare(strict_types=1);

namespace MergeMultisite\Migration;

/**
 * Generates the six redirect-map export formats (PLAN.md §7.6) from a
 * single list of redirect entries — pure formatting, no DB, fully
 * unit-testable. Written together every run where the
 * `generate_redirect_files` config flag is true; you pick whichever
 * your final host or plugin needs at cutover time.
 *
 * Every formatter consumes the same entry shape:
 *
 *     array{old_url:string, new_url:string, blog_id:int, post_id:int, status:int}
 *
 * `status` is the HTTP status to emit (301 for a moved permalink, 410
 * for deliberately removed content). Output is sorted by old_url so
 * generated files are stable run-to-run.
 *
 * @package MergeMultisite
 */
final class RedirectMapBuilder {

	/**
	 * Full structured data: every field of every entry.
	 *
	 * @param array<int, array{old_url:string, new_url:string, blog_id:int, post_id:int, status:int}> $redirects
	 */
	public function toJson( array $redirects ): string {
		return json_encode( $this->sorted( $redirects ), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) . "\n";
	}

	/**
	 * Human-readable Markdown table for review.
	 *
	 * @param array<int, array{old_url:string, new_url:string, blog_id:int, post_id:int, status:int}> $redirects
	 */
	public function toMarkdown( array $redirects ): string {
		$lines = array(
			'| Old URL | New URL | Site | Post ID | Status |',
			'| --- | --- | --- | --- | --- |',
		);

		foreach ( $this->sorted( $redirects ) as $redirect ) {
			$lines[] = sprintf(
				'| %s | %s | %d | %d | %d |',
				$redirect['old_url'],
				$redirect['new_url'],
				$redirect['blog_id'],
				$redirect['post_id'],
				$redirect['status']
			);
		}

		return implode( "\n", $lines ) . "\n";
	}

	/**
	 * Generic two-column `source,target` CSV compatible with the
	 * Redirection plugin's importer (`source URL,target URL` header;
	 * it also accepts trailing `,regex,http code,type` columns, which
	 * we leave off).
	 *
	 * @param array<int, array{old_url:string, new_url:string, blog_id:int, post_id:int, status:int}> $redirects
	 */
	public function toCsv( array $redirects ): string {
		$lines = array( 'source URL,target URL' );

		foreach ( $this->sorted( $redirects ) as $redirect ) {
			$lines[] = $this->csvLine( array( $redirect['old_url'], $redirect['new_url'] ) );
		}

		return implode( "\n", $lines ) . "\n";
	}

	/**
	 * Yoast SEO Premium import format: a fixed 4-column CSV
	 * (`"Origin","Target","Type","Format"` header, one
	 * `"old","new","301","plain"` row per redirect).
	 *
	 * @param array<int, array{old_url:string, new_url:string, blog_id:int, post_id:int, status:int}> $redirects
	 */
	public function toYoastCsv( array $redirects ): string {
		$lines = array( '"Origin","Target","Type","Format"' );

		foreach ( $this->sorted( $redirects ) as $redirect ) {
			$lines[] = $this->csvLine( array( $redirect['old_url'], $redirect['new_url'], (string) $redirect['status'], 'plain' ) );
		}

		return implode( "\n", $lines ) . "\n";
	}

	/**
	 * Apache `mod_alias` block: `Redirect {status} "path" "target"`.
	 * Status 410 maps to the `gone` keyword (no target URL).
	 *
	 * @param array<int, array{old_url:string, new_url:string, blog_id:int, post_id:int, status:int}> $redirects
	 */
	public function toHtaccess( array $redirects ): string {
		$lines = array(
			'# Redirects generated by merge-multisite',
			'<IfModule mod_alias.c>',
		);

		foreach ( $this->sorted( $redirects ) as $redirect ) {
			$path = self::urlPath( $redirect['old_url'] );

			if ( $redirect['status'] === 410 ) {
				$lines[] = sprintf( '    Redirect gone "%s"', $path );
			} else {
				$lines[] = sprintf( '    Redirect %d "%s" "%s"', $redirect['status'], $path, $redirect['new_url'] );
			}
		}

		$lines[] = '</IfModule>';

		return implode( "\n", $lines ) . "\n";
	}

	/**
	 * Nginx rules for inside a `server {}` block: `rewrite` with
	 * `permanent`/`redirect` for 301/302, and an exact-match
	 * `location =` + `return` for non-redirect statuses like 410.
	 *
	 * @param array<int, array{old_url:string, new_url:string, blog_id:int, post_id:int, status:int}> $redirects
	 */
	public function toNginx( array $redirects ): string {
		$lines = array( '# Redirects generated by merge-multisite -- place inside the server {} block.' );

		foreach ( $this->sorted( $redirects ) as $redirect ) {
			$path = self::urlPath( $redirect['old_url'] );

			if ( $redirect['status'] === 301 || $redirect['status'] === 302 ) {
				$flag = $redirect['status'] === 301 ? 'permanent' : 'redirect';
				$lines[] = sprintf( 'rewrite ^%s$ %s %s;', preg_quote( $path ), $redirect['new_url'], $flag );
			} else {
				$lines[] = sprintf( 'location = %s { return %d; }', $path, $redirect['status'] );
			}
		}

		return implode( "\n", $lines ) . "\n";
	}

	/**
	 * Write all six formats into `$directory` (created if needed).
	 *
	 * @param array<int, array{old_url:string, new_url:string, blog_id:int, post_id:int, status:int}> $redirects
	 *
	 * @return string[] The basenames written, in a fixed order.
	 */
	public function writeAll( array $redirects, string $directory ): array {
		if ( ! is_dir( $directory ) ) {
			mkdir( $directory, 0775, true );
		}

		$files = array(
			'redirects.json'       => $this->toJson( $redirects ),
			'redirects.md'         => $this->toMarkdown( $redirects ),
			'redirects.csv'        => $this->toCsv( $redirects ),
			'redirects-yoast.csv'  => $this->toYoastCsv( $redirects ),
			'redirects.htaccess'   => $this->toHtaccess( $redirects ),
			'redirects-nginx.conf' => $this->toNginx( $redirects ),
		);

		foreach ( $files as $name => $contents ) {
			file_put_contents( rtrim( $directory, '/' ) . '/' . $name, $contents );
		}

		return array_keys( $files );
	}

	/**
	 * The URL path used as the match target by the Apache/Nginx
	 * outputs (query strings are intentionally not matched --
	 * mod_alias `Redirect` and `rewrite` work on paths).
	 */
	private static function urlPath( string $url ): string {
		$path = parse_url( $url, PHP_URL_PATH );

		return is_string( $path ) && $path !== '' ? $path : '/';
	}

	/**
	 * @param array<int, array{old_url:string, new_url:string, blog_id:int, post_id:int, status:int}> $redirects
	 *
	 * @return array<int, array{old_url:string, new_url:string, blog_id:int, post_id:int, status:int}>
	 */
	private function sorted( array $redirects ): array {
		$sorted = array_values( $redirects );
		usort(
			$sorted,
			static function ( array $a, array $b ): int {
				$byUrl = strcmp( (string) $a['old_url'], (string) $b['old_url'] );

				return $byUrl !== 0 ? $byUrl : ( (int) $a['post_id'] <=> (int) $b['post_id'] );
			}
		);

		return $sorted;
	}

	/**
	 * @param string[] $fields
	 */
	private function csvLine( array $fields ): string {
		$escaped = array();
		foreach ( $fields as $field ) {
			$escaped[] = '"' . str_replace( '"', '""', $field ) . '"';
		}

		return implode( ',', $escaped );
	}
}
