<?php

declare(strict_types=1);

namespace MergeMultisite\Migration;

/**
 * Renders a list of Site objects as ready-to-paste `sites.php` PHP
 * source -- the same array-literal format `config/sites.php` expects
 * (see PLAN.md §4.2) -- so `--list-sites-php` can be redirected
 * straight into that file instead of being hand-reformatted each time.
 *
 * Deliberately has no I/O of its own (no file writing, no CLI
 * argument handling) so the formatting logic is fully unit-testable;
 * `bin/multisite-integrity-checker.php` handles printing/redirection.
 *
 * @package MergeMultisite
 */
final class SitesPhpExporter {

	/**
	 * @param Site[] $sites Typically every site from
	 *                      SiteSelector::listAllSites() -- deleted
	 *                      sites are skipped since they're already
	 *                      excluded automatically regardless of
	 *                      sites.php (PLAN.md §4.2).
	 */
	public function export( array $sites ): string {
		$lines = array(
			'<?php',
			'',
			'/**',
			' * Site-selection configuration for this run.',
			' *',
			' * Regenerated by:',
			' *   php bin/multisite-integrity-checker.php --list-sites-php > config/sites.php',
			' *',
			' * That command preserves any include/category overrides already',
			' * present in this file, so re-running it after editing is safe --',
			' * it will not silently revert your changes back to the defaults.',
			' *',
			' * @package MergeMultisite',
			' */',
			'',
			'return [',
		);

		foreach ( $sites as $site ) {
			if ( $site->deleted ) {
				continue;
			}

			$lines[] = '    ' . $this->exportEntry( $site ) . ',';
		}

		$lines[] = '];';
		$lines[] = '';

		return implode( "\n", $lines );
	}

	private function exportEntry( Site $site ): string {
		$fields = array(
			'blog_id' => $site->blogId,
			'domain' => $site->domain,
			'include' => $site->included,
			'category_name' => $site->categoryName,
		);

		if ( $site->categorySlug !== null ) {
			$fields['category_slug'] = $site->categorySlug;
		}

		$parts = array();
		foreach ( $fields as $key => $value ) {
			$parts[] = sprintf( '%s => %s', var_export( $key, true ), var_export( $value, true ) );
		}

		return '[' . implode( ', ', $parts ) . ']';
	}
}
