<?php

declare(strict_types=1);

namespace MergeMultisite\Migration;

/**
 * Renders a list of Site objects as ready-to-paste `sites.php` PHP
 * source -- the same array-literal format `config/sites.php` expects
 * (see PLAN.md §4.2) -- so `--list-sites-php` can be redirected
 * straight into that file instead of being hand-reformatted each time.
 *
 * Deliberately has no I/O of its own (no file writing, no CLI
 * argument handling) so the formatting logic is fully unit-testable;
 * `bin/multisite-integrity-checker.php` handles printing/redirection.
 *
 * @package MergeMultisite
 */
final class SitesPhpExporter {

	/**
	 * @param Site[] $sites Typically every site from
	 *                      SiteSelector::listAllSites() -- including
	 *                      deleted ones, which are emitted with
	 *                      'include' => false + 'deleted' => true so the
	 *                      config lists every site for review (PLAN.md
	 *                      §4.2 keeps them excluded automatically).
	 */
	public function export( array $sites ): string {
		$lines = array(
			'<?php',
			'',
			'/**',
			' * Site-selection configuration for this run.',
			' *',
			' * Regenerated by:',
			' *   php bin/multisite-integrity-checker.php --list-sites-php > config/sites.php',
			' *',
			' * That command preserves any include/category overrides already',
			' * present in this file, so re-running it after editing is safe --',
			' * it will not silently revert your changes back to the defaults.',
			' *',
			' * @package MergeMultisite',
			' */',
			'',
			'return array(',
		);

		foreach ( $this->exportEntries( $sites ) as $entry ) {
			$lines[] = '    ' . $entry . ',';
		}

		$lines[] = ');';
		$lines[] = '';

		return implode( "\n", $lines );
	}

	/**
	 * One paste-ready `array( ... )` entry per site -- the same lines
	 * that make up the body of export(). Deleted sites are included,
	 * marked 'include' => false + 'deleted' => true (a documentation
	 * key SiteConfig ignores), so nothing in the network is hidden
	 * from review.
	 *
	 * `--list-sites` prints these directly so entries can be pasted
	 * into an existing config/sites.php, while `--list-sites-php`
	 * wraps them in a complete file.
	 *
	 * @param Site[] $sites
	 *
	 * @return string[]
	 */
	public function exportEntries( array $sites ): array {
		$entries = array();
		foreach ( $sites as $site ) {
			$entries[] = $this->exportEntry( $site );
		}

		return $entries;
	}

	private function exportEntry( Site $site ): string {
		$fields = array(
			'blog_id' => $site->blogId,
			'domain' => $site->domain,
			'include' => $site->included,
		);

		if ( $site->deleted ) {
			$fields['deleted'] = true;
		}

		$fields['category_name'] = $site->categoryName;

		if ( $site->categorySlug !== null ) {
			$fields['category_slug'] = $site->categorySlug;
		}

		$parts = array();
		foreach ( $fields as $key => $value ) {
			$parts[] = sprintf( '%s => %s', var_export( $key, true ), var_export( $value, true ) );
		}

		return 'array( ' . implode( ', ', $parts ) . ' )';
	}
}
